name: Develop ci/cd

on:
  push:
    branches: "main"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/tutor-backend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tutor-backend

  deploy:
    name: CD
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: CD
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/tutor-backend
            docker stop back || true
            docker container rm back || true
            docker run -dit -p 8080:8080 --name back ${{secrets.DOCKERHUB_USERNAME}}/tutor-backend
            docker image prune -f